dist: trusty
sudo: required

branches:
  except:
  - master-step1
  - master-step2

language: node_js
node_js:
  - "8"

cache:
  directories:
     - ./node_modules

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - npm run test
