dist: trusty
sudo: required

language: node_js
node_js:
  - "8"

cache:
  directories:
     - ./node_modules

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - npm run test
